Moved update and install to functions.

diff --git a/bash_helpers b/bash_helpers
--- a/bash_helpers
+++ b/bash_helpers
@@ -1,4 +1,3 @@
-
 #!/bin/bash
 
 
@@ -296,24 +295,6 @@ os_version()
 }
 
 
-path()
-{
-    if ! [[ "$TERMUX_VERSION" == "" ]];
-    then
-        echo "$PREFIX/opt/bin/bash_helpers"
-        
-    else
-        if [[ "$HOME" == "/root" ]];
-        then
-            echo "/opt/bin/bash_helpers"
-            
-        else
-            echo "$HOME/.local/bin/bash_helpers"
-        fi
-    fi
-}
-
-
 pause()
 {
     read -p "Press ENTER to continue. Ctrl-C to abort."
@@ -374,6 +355,111 @@ uppercase()
     then
         echo "$1" | awk '{print toupper($0)}'
     fi
+}
+
+
+install()
+{
+	if ! [[ -f "$HOME/.bashrc" ]] && [[ -v TERMUX_VERSION ]];
+    then
+        cp "$PREFIX/etc/bash.bashrc" "$HOME/.bashrc"
+    fi
+
+    if ! [[ -f "$HOME/.environment" ]];
+    then
+        touch "$HOME/.environment"
+    fi
+        
+    SCRIPT=$(realpath $0)
+    FILENAME=$(basename "$SCRIPT")
+
+    INSTALL_PATH=$(dirname $(path))
+
+    if [[ -v SUPER_USER ]];
+    then
+        PERMS="755"
+        SUDO="sudo"
+    else
+        PERMS="770"
+    fi
+
+    if ! [[ -d "$INSTALL_PATH" ]];
+    then
+        mkdir -p "$INSTALL_PATH"
+    fi
+
+    $SUDO cp $SCRIPT $INSTALL_PATH/
+    $SUDO chmod $PERMS "$INSTALL_PATH/${FILENAME}"
+
+    if [[ "$?" == "0" ]];
+    then
+		if [[ -d "$HOME/.envs" ]] && ! [[ -f "$HOME/.envs/bash_helpers" ]];
+		then
+		    URL="https://raw.githubusercontent.com/aribrew/bash_scripting"
+            URL+="/refs/heads/main/.bash_helpers.env"
+
+			curl -LO $URL
+
+			if [[ "$?" == "0" ]];
+			then
+			    mv .bash_helpers.env $HOME/.envs/bash_helpers
+			fi
+
+			if [[ -f ".bash_helpers.env" ]];
+			then
+			    rm ".bash_helpers.env"
+			fi
+		fi
+    fi
+}
+
+
+path()
+{
+    if ! [[ "$TERMUX_VERSION" == "" ]];
+    then
+        echo "$PREFIX/opt/bin/bash_helpers"
+        
+    else
+        if [[ "$HOME" == "/root" ]];
+        then
+            echo "/opt/bin/bash_helpers"
+            
+        else
+            echo "$HOME/.local/bin/bash_helpers"
+        fi
+    fi
+}
+
+
+update()
+{
+	cd /tmp
+	
+	URL="https://raw.githubusercontent.com/aribrew/bash_scripting"
+	URL+="/refs/heads/main/bash_helpers"
+	
+	echo -e "Downloading latest bash_helpers ..."
+	echo -e "-----------------------------------"
+	    
+	curl -LO $URL
+	
+	if [[ "$?" == "0" ]];
+	then
+	    INSTALL_PATH=$(path)
+	
+	    cp -u bash_helpers "$INSTALL_PATH"
+	
+	    if [[ "$?" == "0" ]];
+	    then
+	        echo -e "Done!\n"
+	    else
+	        abort "Something is wrong. Unable to update local script.\n"
+	    fi
+	else
+	    rm /tmp/bash_helpers
+	    abort "Failed!"
+	fi
 }
 
 
@@ -456,87 +542,9 @@ then
     
 elif [[ "$1" == "--install" ]];
 then
-    if ! [[ -f "$HOME/.bashrc" ]] && [[ -v TERMUX_VERSION ]];
-    then
-        cp "$PREFIX/etc/bash.bashrc" "$HOME/.bashrc"
-    fi
-
-    if ! [[ -f "$HOME/.environment" ]];
-    then
-        touch "$HOME/.environment"
-    fi
-        
-    SCRIPT=$(realpath $0)
-    FILENAME=$(basename "$SCRIPT")
-
-    INSTALL_PATH=$(dirname $(path))
-
-    if [[ -v SUPER_USER ]];
-    then
-        PERMS="755"
-        SUDO="sudo"
-    else
-        PERMS="770"
-    fi
-
-    if ! [[ -d "$INSTALL_PATH" ]];
-    then
-        mkdir -p "$INSTALL_PATH"
-    fi
-
-    $SUDO cp $SCRIPT $INSTALL_PATH/
-    $SUDO chmod $PERMS "$INSTALL_PATH/${FILENAME}"
-
-    if [[ "$?" == "0" ]];
-    then
-	    if ! [[ -d "$HOME/.envs" ]];
-		then
-		    mkdir -p "$HOME/.envs'
-	    fi
-
-		if ! [[ -f "$HOME/.envs/bash_helpers" ]];
-		then
-		    URL="https://raw.githubusercontent.com/aribrew/bash_scripting"
-            URL+="/refs/heads/main/.bash_helpers.env"
-
-			curl -LO $URL
-
-			if [[ "$?" == "0" ]];
-			    mv .bash_helpers.env $HOME/.envs/bash_helpers
-			fi
-
-			if [[ -f ".bash_helpers.env" ]];
-			    rm ".bash_helpers.env"
-			fi
-		fi
-    fi
+    install
 
 elif [[ "$1" == "--update" ]];
 then
-    cd /tmp
-
-    URL="https://raw.githubusercontent.com/aribrew/bash_scripting"
-    URL+="/refs/heads/main/bash_helpers"
-
-    echo -e "Downloading latest bash_helpers.sh ..."
-    echo -e "--------------------------------------"
-    
-    curl -LO $URL
-
-    if [[ "$?" == "0" ]];
-    then
-        INSTALL_PATH=$(path)
-
-        cp -u bash_helpers "$INSTALL_PATH"
-
-        if [[ "$?" == "0" ]];
-        then
-            echo -e "Done!\n"
-        else
-            abort "Something is wrong. Unable to update local script.\n"
-        fi
-    else
-        rm /tmp/bash_helpers
-        abort "Failed!"
-    fi
+    update
 fi
